echo "  - Install luci-compat"
opkg install luci-compat

install_app_by_cond "${INSTALL_LUCI_WOL}" wol
install_app_by_cond "${INSTALL_LUCI_UHTTPD}" uhttpd
install_app_by_cond "${INSTALL_LUCI_WIREGUARD}" wireguard
install_app_by_cond "${INSTALL_LUCI_SAMBA4}" samba4
install_app_by_cond "${INSTALL_LUCI_MINIDLNA}" minidlna
install_app_by_cond "${INSTALL_LUCI_UPNP}" upnp
install_app_by_cond "${INSTALL_LUCI_WATCHCAT}" watchcat
install_app_by_cond "${INSTALL_LUCI_TTYD}" ttyd
install_app_by_cond "${INSTALL_LUCI_FRPC}" frpc
install_app_by_cond "${INSTALL_LUCI_FRPS}" frps
install_app_by_cond "${INSTALL_LUCI_QOS}" qos
install_app_by_cond "${INSTALL_LUCI_NFT_QOS}" nft-qos
install_app_by_cond "${INSTALL_LUCI_NLBWMON}" nlbwmon
install_app_by_cond "${INSTALL_LUCI_COMMANDS}" commands
install_app_by_cond "${INSTALL_LUCI_MWAN3}" mwan3
install_app_by_cond "${INSTALL_LUCI_PRIVOXY}" privoxy
download_and_install_by_cond "${INSTALL_LUCI_ALIDDNS}" "https://github.com/honwen/luci-app-aliddns/releases/download/v20210117/luci-app-aliddns_0.4.0-1_all.ipk"
install_app_by_cond "${INSTALL_LUCI_DDNS}" ddns
install_by_cond "${INSTALL_DDNS_SCRIPTS}" ddns-scripts
install_by_cond "${INSTALL_DDNS_SCRIPTS_CLOUDFLARE}" ddns-scripts-cloudflare
install_by_cond "${INSTALL_DDNS_SCRIPTS_CNKUAI}" ddns-scripts-cnkuai
install_by_cond "${INSTALL_DDNS_SCRIPTS_DIGITALOCEAN}" ddns-scripts-digitalocean
install_by_cond "${INSTALL_DDNS_SCRIPTS_FREEDNS}" ddns-scripts-freedns
install_by_cond "${INSTALL_DDNS_SCRIPTS_GANDI}" ddns-scripts-gandi
install_by_cond "${INSTALL_DDNS_SCRIPTS_GODADDY}" ddns-scripts-godaddy
install_by_cond "${INSTALL_DDNS_SCRIPTS_NOIP}" ddns-scripts-noip
install_by_cond "${INSTALL_DDNS_SCRIPTS_NSUPDATE}" ddns-scripts-nsupdate
install_by_cond "${INSTALL_DDNS_SCRIPTS_ROUTE53}" ddns-scripts-route53
