name: OpenWrt-22

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    schedule:
        -   cron: '0 16 * * *'

jobs:
    openwrt-22-x86-64-generic-ext4-combined-mbr:
        runs-on: ubuntu-latest
        env:
            base_img_url: 'https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/openwrt-22.03.2-x86-64-generic-ext4-combined.img.gz'
            base_img_name: 'openwrt-22.03.2-x86-64-generic-ext4-combined'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Download base image
                run: |
                    wget -t 30 -w 5 -O "imgs/${base_img_name}.img.gz" "${base_img_url}"
            -   name: Build
                run: |
                    ./docker_openwrt_kitchen.sh "imgs/${base_img_name}.img.gz"
            -   name: Upload
                uses: actions/upload-artifact@v3
                with:
                    name: ${{env.base_img_name}}
                    path: dist/${{env.base_img_name}}-cooked.img
    openwrt-22-x86-64-generic-ext4-combined-mbr-zh-cn:
        runs-on: ubuntu-latest
        env:
            base_img_url: 'https://downloads.openwrt.org/releases/22.03.2/targets/x86/64/openwrt-22.03.2-x86-64-generic-ext4-combined.img.gz'
            base_img_name: 'openwrt-22.03.2-x86-64-generic-ext4-combined-zh-cn'
            user_config: 'config.zh-cn.sh'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Apply config ${user_config}
                run: |
                    ln -s configs/${user_config} config.user.sh
            -   name: Download base image
                run: |
                    wget -t 30 -w 5 -O "imgs/${base_img_name}.img.gz" "${base_img_url}"
            -   name: Build
                run: |
                    ./docker_openwrt_kitchen.sh "imgs/${base_img_name}.img.gz"
            -   name: Upload
                uses: actions/upload-artifact@v3
                with:
                    name: ${{env.base_img_name}}
                    path: dist/${{env.base_img_name}}-cooked.img
